version: '2'
services:
  arts:
    build: .
    volumes:
     - ./images:/images
    devices:
     - "/dev/nvidiactl:/dev/nvidiactl"
     - "/dev/nvidia-uvm:/dev/nvidia-uvm"
     - "/dev/nvidia0:/dev/nvidia0"

